#!/usr/bin/python3

import sys
import os
import shutil


def get_server_source_files(env):
    dirs = []
    for root, _, _ in os.walk('.'):
        dirs.append(root)

    source_files = []
    for d in dirs:
        source_files.extend(env.Glob(os.path.join(d, '*.cpp'), exclude=['main.cpp']))

    return source_files

def copy_glad():
    if not os.path.isdir('../build/render/glad'):
        shutil.copytree('../src/render/glad', '../build/render/glad')

copy_glad()

env = Environment(parse_flags='-lboost_thread.a -std=c++17 ')
server_source_files = get_server_source_files(env)

env['ENV']['TERM'] = os.environ['TERM']
# env.Append(CCFLAGS='-O3')
env.Append(LIBS=['pthread', 'GLU', 'glfw3', 'X11', 'Xxf86vm', 'Xrandr', 'pthread', 'Xi', 'dl', 'Xinerama', 'Xcursor']),

env.Program('server', server_source_files)
