#!/usr/bin/python3

import sys
import os

env = Environment(parse_flags='-lboost_thread.a -std=c++17')
server_source_files = env.Glob('*.cpp', exclude=['main.cpp'])

env['ENV']['TERM'] = os.environ['TERM']
# env.Append(CCFLAGS='-O3')
env.Append(LIBS=['pthread'])

env.Program('server', server_source_files)
